### ISSUE TITLE
About the problems encountered after ./configure em_real

### ISSUE THREAD

**Issue by yangning-code** [WRF-GC/wrf-gc-release#11]
The compilation was successful in the end, as shown in the compile figure, but there are still some errors in the log file of the entire compilation, as shown in the error figure. I don’t know if this will have any impact, or how we can solve this bug?
![compile](https://github.com/user-attachments/assets/90486b9f-7831-44fa-985f-df6b2b27043e)
![error](https://github.com/user-attachments/assets/61f4934c-39bd-47e4-86dd-03f15d9a0a54)

**Comment by jimmielin** [comment]
If the real.exe and wrf.exe are successfully built then there is no issue - GCHP interface folder is not used in WRF-GC so there is nothing to resolve here.
