### ISSUE TITLE
an array index going out of bounds in the SOURCE_2D_4 array

### ISSUE THREAD

**Issue by Dengx886** [WRF-GC/wrf-gc-release#9]
Respected sir/madam,
When I run the three-level nested wrf.exe, I encounter the error: “forrtl: severe (408): fort: (2): Subscript #2 of the array SOURCE_2D_4 has value 57 which is greater than the upper bound of 40.” After reducing e_we and e_sn in the namelist, similar errors still occur. How can I resolve this?
Thanks.
<img width="889" alt="image" src="https://github.com/user-attachments/assets/88d5ec4a-40f4-4698-8d27-c3eff73a5267">
<img width="882" alt="微信图片_20241028103224" src="https://github.com/user-attachments/assets/1bb8eee6-465f-4da4-9cbb-3807eda3bd09">

**Comment by jimmielin** [comment]
This has been fixed by @topleo and the fix is now available in https://github.com/WRF-GC/wrf-gc-release/commit/ddb851fa9a8aa1366c70a70238d4359757d9b59f.
